locustfile = ./scenarios/http/gateway/new_user_make_top_up_operation/scenario.py
spawn-rate = 10
run-time = 3m
headless = true
users = 100
html = ./scenarios/http/gateway/new_user_make_top_up_operation/report.html
# Имя для CSV-отчётов (будет добавлено в начало имени каждого файла отчёта)
csv = locust_http_gateway_new_user_make_top_up_operation
# Включаем генерацию CSV с историей значений по времени
csv-full-history = true
